### ISSUE TITLE
Support for custom comment format

### ISSUE THREAD

**Issue by R3dst0ne** [MarcinOrlowski/prop-tool#2]
> NOTE: as this is quite common that translation file may not be updated instantly, prop-tool considers key presence condition fulfilled also when given key exists in B file but is commented out and follow expected comment format:
`# ==> KEY =`

This is a great feature. Making the comment format customizable would make it even better.

**Comment by MarcinOrlowski** [comment]
Good idea. I will make it configurable. For now it's made for what we needed in logisim-evolution

**Comment by MarcinOrlowski** [comment]
Fixed in 1.1.0
