### ISSUE TITLE
Brackets and quotation mark check

### ISSUE THREAD

**Issue by R3dst0ne** [MarcinOrlowski/prop-tool#5]
Check if opened brackets/quotation-marks (`(`, `[`, `{`, `"`, `'`) get closed (and the other way around).
`<` could be considered too, but I'm not sure about this one because it often gets used otherwise.

**Comment by MarcinOrlowski** [comment]
Good idea. It's actually easy to check incl. proper order too.

**Comment by MarcinOrlowski** [comment]
Added in `dev/` branch:

```bash
Base: brackets.properties
  Errors: 4, warnings: 1
    Brackets
      E: Line 2:1: "missingClosing": No closing bracket for "(".
      W: Line 3:16: No closing bracket for "<"
      E: Line 4:4: "missingOpening": No opening bracket matching ")".
      E: Line 5:3: "mixedOrder: Incorrect type. Expected ")", found ">".
      E: Line 5:1: "mixedOrder": No closing bracket for "<".
```

**Comment by MarcinOrlowski** [comment]
One problem with dealing of quotation marks is the apostrophe `'` as in some languages (i.e. English) it is used elsewhere as well. For I see no simple workaround for this except for excluding `'` from known quotation marks.

**Comment by MarcinOrlowski** [comment]
QuotationMarks check added in dev/ 

Follow-up on apostrophes support in #8
